### ISSUE TITLE
下载完成后闪退了

### ISSUE THREAD

**Issue by uaoan** [JeffMony/VideoDownloader#47]
我在下载完成后就闪退出来了，下面是闪退的日志，不知道是什么情况
[图片](https://uaoan-fatcat-sex-1253865537.cos.ap-nanjing.myqcloud.com/Screenshotbug.jpg) 

闪退日志

Build version: 1.0 
Build date: 2016-07-02 20:43:26 
Current date: 2023-03-10 18:53:26 
Device: Vivo V2171A 
Stack trace:  
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jeffmony/m3u8library/VideoProcessManager;
	at com.jeffmony.downloader.VideoDownloadManager.doMergeTs(VideoDownloadManager.java:650)
	at com.jeffmony.downloader.VideoDownloadManager.handleOnDownloadSuccess(VideoDownloadManager.java:624)
	at com.jeffmony.downloader.VideoDownloadManager.access$1100(VideoDownloadManager.java:43)
	at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.dispatchDownloadMessage(VideoDownloadManager.java:581)
	at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.handleMessage(VideoDownloadManager.java:533)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.ClassNotFoundException: com.jeffmony.m3u8library.VideoProcessManager
	... 9 more

**Comment by JeffMony** [comment]
是不是被混淆了？keep一下。

**Comment by uaoan** [comment]
我把自动合并打开了，下载完成就闪退了，关闭了下载完成后就没事，但是也只是某些部分m3u8才会闪退，有的可以直接合并。

@JeffMony

**Comment by JeffMony** [comment]
可以贴几个合并会导致crash的m3u8 链接吗？
我测试一下，可以下载的。

**Comment by uaoan** [comment]
https://s.xlzys.com/play/9avDmPgd/index.m3u8
上面这个合并闪退了

https://s.xlzys.com/play/5eVllGob/index.m3u8
这个就可以
@JeffMony

**Comment by JeffMony** [comment]
https://github.com/JeffMony/VideoDownloader/commit/83b11ade38c7b9e2905808a567e55e549b00e02e

这个commit已经修复了你的问题。

**Comment by uaoan** [comment]
好的👌🏻  @JeffMony
