### ISSUE TITLE
请教关于无法播放下载的视频问题

### ISSUE THREAD

**Issue by haxhw** [JeffMony/VideoDownloader#56]
问题描述：
1 在Player播放页面修改播放器的内核为 EXO内核 
修改代码：mPlayer = new CommonPlayer(this, PlayerType.EXO_PLAYER);

2 点击播放按钮无法播放下载合并的mp4的视频，报错信息
com.jeffmony.videodemo E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalArgumentException
.....
com.jeffmony.videodemo E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalArgumentException....

**Comment by JeffMony** [comment]
给一个例子了。
