### ISSUE TITLE
会出现崩溃，使用Demo里面出现的

### ISSUE THREAD

**Issue by Arey688** [JeffMony/VideoDownloader#57]
<img width="1894" alt="image" src="https://github.com/JeffMony/VideoDownloader/assets/142769289/5a6a290d-cf08-4e42-973c-06d214b905d3">

**Comment by JeffMony** [comment]
是不是类被混淆了？确认一下自己的依赖库是不是 5.8.0

**Comment by Arey688** [comment]
下载的最新的demo ，使用的是VideoDownloader中的Demo跑的，必现，选择代码里面的普通下载，然后依次点击列表中的下载，超过一定数量就崩溃了

**Comment by JeffMony** [comment]
好的，完整的crash堆栈贴一下

**Comment by Arey688** [comment]
`2023-08-29 17:47:11.342 14928-14928 RenderThread            com.jeffmony.videodemo               W  type=1400 audit(0.0:72136): avc: denied { getattr } for path="/sys/module/metis/parameters/minor_window_app" dev="sysfs" ino=78156 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:sysfs_migt:s0 tclass=file permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:11.346 14928-14928 RenderThread            com.jeffmony.videodemo               W  type=1400 audit(0.0:72137): avc: denied { getattr } for path="/sys/module/metis/parameters/minor_window_app" dev="sysfs" ino=78156 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:sysfs_migt:s0 tclass=file permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:11.350 14928-14953 DownloadFeatureActivity com.jeffmony.videodemo               W  onDownloadPending: VideoTaskItem[Url=https://v3.cdtlas.com/20221119/zimPf0a2/1100kb/hls/index.m3u8, Type=0, Percent=0.0, DownloadSize=0, State=-1, FilePath=null, LocalFile=null, CoverUrl=https://i.loli.net/2021/04/18/WuAUZc85meB6D2Q.jpg, CoverPath=null, Title=test1]
2023-08-29 17:47:11.350 14928-14928 RenderThread            com.jeffmony.videodemo               W  type=1400 audit(0.0:72138): avc: denied { getattr } for path="/sys/module/metis/parameters/minor_window_app" dev="sysfs" ino=78156 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:sysfs_migt:s0 tclass=file permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:11.354 14928-14928 RenderThread            com.jeffmony.videodemo               W  type=1400 audit(0.0:72139): avc: denied { getattr } for path="/sys/module/metis/parameters/minor_window_app" dev="sysfs" ino=78156 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:sysfs_migt:s0 tclass=file permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:11.361 14928-15195 DpmTcmClient            com.jeffmony.videodemo               I  RegisterTcmMonitor from: $Proxy2
2023-08-29 17:47:11.367 14928-15195 TrafficStats            com.jeffmony.videodemo               D  tagSocket(111) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:11.362 14928-14928 RenderThread            com.jeffmony.videodemo               W  type=1400 audit(0.0:72140): avc: denied { getattr } for path="/sys/module/metis/parameters/minor_window_app" dev="sysfs" ino=78156 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:sysfs_migt:s0 tclass=file permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:11.643 14928-15195 TrafficStats            com.jeffmony.videodemo               D  tagSocket(96) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:11.980 14928-14953 DownloadFeatureActivity com.jeffmony.videodemo               W  onDownloadPending: VideoTaskItem[Url=https://vod.soundstage.cn/f7695410d4f371ed8d6c16b5feac0102/video/81eb3c63bfd74856b5d7922b04155f65-4f17abef18d33e3f2151dbde92e4ccbd-video-ld.m3u8?auth_key=1681890446-e93a1a43c99f4d75afad9322c0e8d1cb-0-c328fa251abf466fbf909c12933186b1, Type=0, Percent=0.0, DownloadSize=0, State=-1, FilePath=null, LocalFile=null, CoverUrl=https://i.loli.net/2021/04/18/WuAUZc85meB6D2Q.jpg, CoverPath=null, Title=test2]
2023-08-29 17:47:11.987 14928-15206 TrafficStats            com.jeffmony.videodemo               D  tagSocket(98) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:12.164 14928-15195 video_downloader        com.jeffmony.videodemo               I  doParseVideoInfoTask url=https://v3.cdtlas.com/20221119/zimPf0a2/1100kb/hls/index.m3u8
2023-08-29 17:47:12.167 14928-15195 TrafficStats            com.jeffmony.videodemo               D  tagSocket(112) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:12.256 14928-15206 video_downloader        com.jeffmony.videodemo               I  doParseVideoInfoTask url=https://vod.soundstage.cn/f7695410d4f371ed8d6c16b5feac0102/video/81eb3c63bfd74856b5d7922b04155f65-4f17abef18d33e3f2151dbde92e4ccbd-video-ld.m3u8?auth_key=1681890446-e93a1a43c99f4d75afad9322c0e8d1cb-0-c328fa251abf466fbf909c12933186b1
2023-08-29 17:47:12.259 14928-15206 TrafficStats            com.jeffmony.videodemo               D  tagSocket(113) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:12.626 14928-14953 DownloadFeatureActivity com.jeffmony.videodemo               W  onDownloadPending: VideoTaskItem[Url=https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8, Type=0, Percent=0.0, DownloadSize=0, State=-1, FilePath=null, LocalFile=null, CoverUrl=https://i.loli.net/2021/04/18/WuAUZc85meB6D2Q.jpg, CoverPath=null, Title=test3]
2023-08-29 17:47:12.694 14928-15220 video_downloader        com.jeffmony.videodemo               I  doParseVideoInfoTask url=https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8
2023-08-29 17:47:12.695 14928-15220 TrafficStats            com.jeffmony.videodemo               D  tagSocket(116) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:12.764 14928-15206 TrafficStats            com.jeffmony.videodemo               D  tagSocket(147) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:12.941 14928-15220 TrafficStats            com.jeffmony.videodemo               D  tagSocket(113) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:13.229 14928-15195 TrafficStats            com.jeffmony.videodemo               D  tagSocket(112) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:13.231 14928-15220 TrafficStats            com.jeffmony.videodemo               D  tagSocket(120) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:13.421 14928-15220 video_downloader        com.jeffmony.videodemo               I  parseNetworkM3U8Info responseCode=200
2023-08-29 17:47:13.423 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXTM3U
2023-08-29 17:47:13.423 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2149280,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=1280x720,NAME="720"
2023-08-29 17:47:13.423 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = url_0/193039199_mp4_h264_aac_hd_7.m3u8
2023-08-29 17:47:13.453 14928-15206 TrafficStats            com.jeffmony.videodemo               D  tagSocket(116) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:13.454 14928-15220 video_downloader        com.jeffmony.videodemo               I  parseNetworkM3U8Info responseCode=200
2023-08-29 17:47:13.454 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXTM3U
2023-08-29 17:47:13.454 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXT-X-VERSION:3
2023-08-29 17:47:13.455 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXT-X-PLAYLIST-TYPE:VOD
2023-08-29 17:47:13.455 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXT-X-TARGETDURATION:11
2023-08-29 17:47:13.455 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXTINF:10.000,
2023-08-29 17:47:13.456 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = url_462/193039199_mp4_h264_aac_hd_7.ts
2023-08-29 17:47:13.456 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXTINF:10.000,
2023-08-29 17:47:13.456 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = url_463/193039199_mp4_h264_aac_hd_7.ts
2023-08-29 17:47:13.456 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXTINF:10.000,
2023-08-29 17:47:13.456 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = url_464/193039199_mp4_h264_aac_hd_7.ts
2023-08-29 17:47:13.458 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXTINF:10.000,
2023-08-29 17:47:13.464 14928-15220 video_downloader        com.jeffmony.videodemo               I  line = #EXT-X-ENDLIST
2023-08-29 17:47:13.465 14928-14953 DownloadFeatureActivity com.jeffmony.videodemo               W  onDownloadPrepare: VideoTaskItem[Url=https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8, Type=1, Percent=0.0, DownloadSize=0, State=1, FilePath=null, LocalFile=null, CoverUrl=https://i.loli.net/2021/04/18/WuAUZc85meB6D2Q.jpg, CoverPath=/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/26d0eea3413d57f972c13868d23e2da7.jpg, Title=test3]
2023-08-29 17:47:13.466 14928-14953 DownloadFeatureActivity com.jeffmony.videodemo               W  onDownloadStart: VideoTaskItem[Url=https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8, Type=1, Percent=0.0, DownloadSize=0, State=2, FilePath=null, LocalFile=null, CoverUrl=https://i.loli.net/2021/04/18/WuAUZc85meB6D2Q.jpg, CoverPath=/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/26d0eea3413d57f972c13868d23e2da7.jpg, Title=test3]
2023-08-29 17:47:13.474 14928-15220 video_downloader        com.jeffmony.videodemo               I  M3U8VideoDownloadTask local file.
2023-08-29 17:47:13.485 14928-14953 DownloadFeatureActivity com.jeffmony.videodemo               W  onDownloadProgress: 100.00%, curTs=64, totalTs=64
2023-08-29 17:47:13.486 14928-14953 video_downloader        com.jeffmony.videodemo               W  removeDownloadQueue size=2,0,2
2023-08-29 17:47:13.487 14928-15239 video_downloader        com.jeffmony.videodemo               I  doParseVideoInfoTask url=https://v3.cdtlas.com/20221119/zimPf0a2/1100kb/hls/index.m3u8
2023-08-29 17:47:13.487 14928-14953 video_downloader        com.jeffmony.videodemo               I  handleOnDownloadSuccess shouldM3U8Merged=true, isHlsType=true
2023-08-29 17:47:13.487 14928-15240 video_downloader        com.jeffmony.videodemo               I  doParseVideoInfoTask url=https://v3.cdtlas.com/20221119/zimPf0a2/1100kb/hls/index.m3u8
2023-08-29 17:47:13.487 14928-14953 video_downloader        com.jeffmony.videodemo               I  VideoMerge doMergeTs taskItem=VideoTaskItem[Url=https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8, Type=1, Percent=100.0, DownloadSize=175072190, State=5, FilePath=26d0eea3413d57f972c13868d23e2da7_local.m3u8, LocalFile=/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/26d0eea3413d57f972c13868d23e2da7/26d0eea3413d57f972c13868d23e2da7_local.m3u8, CoverUrl=https://i.loli.net/2021/04/18/WuAUZc85meB6D2Q.jpg, CoverPath=/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/26d0eea3413d57f972c13868d23e2da7.jpg, Title=test3]
2023-08-29 17:47:13.487 14928-14953 fmony.videodemo         com.jeffmony.videodemo               I  Rejecting re-init on previously-failed class java.lang.Class<com.jeffmony.m3u8library.VideoProcessManager>: java.lang.ExceptionInInitializerError: 
                                                                                                      at com.jeffmony.m3u8library.VideoProcessManager com.jeffmony.m3u8library.VideoProcessManager.getInstance() (VideoProcessManager.java:27)
                                                                                                      at void com.jeffmony.downloader.VideoDownloadManager.doMergeTs(com.jeffmony.downloader.model.VideoTaskItem, com.jeffmony.downloader.listener.IM3U8MergeResultListener) (VideoDownloadManager.java:647)
                                                                                                      at void com.jeffmony.downloader.VideoDownloadManager.access$1400(com.jeffmony.downloader.VideoDownloadManager, com.jeffmony.downloader.model.VideoTaskItem, com.jeffmony.downloader.listener.IM3U8MergeResultListener) (VideoDownloadManager.java:41)
                                                                                                      at void com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.lambda$dispatchDownloadInfos$2$VideoDownloadManager$VideoDownloadHandler() (VideoDownloadManager.java:539)
                                                                                                      at void com.jeffmony.downloader.-$$Lambda$VideoDownloadManager$VideoDownloadHandler$2NVKttZeyL8RxW86oOV8520RK1o.run() (lambda:-1)
                                                                                                      at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:463)
                                                                                                      at void java.util.concurrent.FutureTask.run() (FutureTask.java:264)
                                                                                                      at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1137)
                                                                                                      at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:637)
                                                                                                      at void java.lang.Thread.run() (Thread.java:1012)
                                                                                                      at void com.jeffmony.downloader.utils.WorkerThreadHandler$MediaWorkerThread.run() (WorkerThreadHandler.java:67)
2023-08-29 17:47:13.489 14928-14953 AndroidRuntime          com.jeffmony.videodemo               E  FATAL EXCEPTION: Video_download_state_thread
                                                                                                    Process: com.jeffmony.videodemo, PID: 14928
                                                                                                    java.lang.NoClassDefFoundError: com.jeffmony.m3u8library.VideoProcessManager
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager.doMergeTs(VideoDownloadManager.java:647)
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager.handleOnDownloadSuccess(VideoDownloadManager.java:621)
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager.access$1100(VideoDownloadManager.java:41)
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.dispatchDownloadMessage(VideoDownloadManager.java:578)
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.handleMessage(VideoDownloadManager.java:530)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.ExceptionInInitializerError
                                                                                                    	at com.jeffmony.m3u8library.VideoProcessManager.getInstance(VideoProcessManager.java:27)
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager.doMergeTs(VideoDownloadManager.java:647)
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager.access$1400(VideoDownloadManager.java:41)
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.lambda$dispatchDownloadInfos$2$VideoDownloadManager$VideoDownloadHandler(VideoDownloadManager.java:539)
                                                                                                    	at com.jeffmony.downloader.-$$Lambda$VideoDownloadManager$VideoDownloadHandler$2NVKttZeyL8RxW86oOV8520RK1o.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	at com.jeffmony.downloader.utils.WorkerThreadHandler$MediaWorkerThread.run(WorkerThreadHandler.java:67)
                                                                                                    Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[video_download_worker_pool_thread,5,main] that has not called Looper.prepare()
                                                                                                    	at android.os.Handler.<init>(Handler.java:227)
                                                                                                    	at android.os.Handler.<init>(Handler.java:129)
                                                                                                    	at com.jeffmony.m3u8library.VideoProcessManager.<clinit>(VideoProcessManager.java:14)
                                                                                                    	at com.jeffmony.m3u8library.VideoProcessManager.getInstance(VideoProcessManager.java:27) 
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager.doMergeTs(VideoDownloadManager.java:647) 
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager.access$1400(VideoDownloadManager.java:41) 
                                                                                                    	at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.lambda$dispatchDownloadInfos$2$VideoDownloadManager$VideoDownloadHandler(VideoDownloadManager.java:539) 
                                                                                                    	at com.jeffmony.downloader.-$$Lambda$VideoDownloadManager$VideoDownloadHandler$2NVKttZeyL8RxW86oOV8520RK1o.run(Unknown Source:2) 
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    	at com.jeffmony.downloader.utils.WorkerThreadHandler$MediaWorkerThread.run(WorkerThreadHandler.java:67) 
2023-08-29 17:47:13.489 14928-15239 TrafficStats            com.jeffmony.videodemo               D  tagSocket(129) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:13.489 14928-15240 TrafficStats            com.jeffmony.videodemo               D  tagSocket(163) with statsTag=0xffffffff, statsUid=-1
2023-08-29 17:47:13.482 14928-14928 Video_download_         com.jeffmony.videodemo               W  type=1400 audit(0.0:72200): avc: denied { search } for name="miuilog" dev="dm-68" ino=402 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:13.486 14928-14928 Video_download_         com.jeffmony.videodemo               W  type=1400 audit(0.0:72201): avc: denied { search } for name="miuilog" dev="dm-68" ino=402 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:13.486 14928-14928 Video_download_         com.jeffmony.videodemo               W  type=1400 audit(0.0:72202): avc: denied { search } for name="miuilog" dev="dm-68" ino=402 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:13.486 14928-14928 Video_download_         com.jeffmony.videodemo               W  type=1400 audit(0.0:72203): avc: denied { search } for name="miuilog" dev="dm-68" ino=402 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:13.486 14928-14928 Video_download_         com.jeffmony.videodemo               W  type=1400 audit(0.0:72204): avc: denied { search } for name="miuilog" dev="dm-68" ino=402 scontext=u:r:untrusted_app_30:s0:c74,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.jeffmony.videodemo
2023-08-29 17:47:13.490 14928-14953 OOMEventManagerFK       com.jeffmony.videodemo               W  Failed to mkdir /data/miuilog/stability/memleak/heapdump/
2023-08-29 17:47:13.507 14928-14953 Process                 com.jeffmony.videodemo               I  Process is going to kill itself!
                                                                                                    java.lang.Exception
                                                                                                    	at android.os.Process.killProcess(Process.java:1344)
                                                                                                    	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181)
                                                                                                    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
                                                                                                    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                                                                    	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
2023-08-29 17:47:13.507 14928-14953 Process                 com.jeffmony.videodemo               I  Sending signal. PID: 14928 SIG: 9
---------------------------- PROCESS ENDED (14928) for package com.jeffmony.videodemo ----------------------------
---------------------------- PROCESS STARTED (15253) for package com.jeffmony.videodemo ----------------------------`

**Comment by Arey688** [comment]
onDownloadPrepare: VideoTaskItem[Url=https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8, Type=1, Percent=0.0, DownloadSize=0, State=1, FilePath=null, LocalFile=null, CoverUrl=https://i.loli.net/2021/04/18/WuAUZc85meB6D2Q.jpg, CoverPath=/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/26d0eea3413d57f972c13868d23e2da7.jpg, Title=test3]
onDownloadStart: VideoTaskItem[Url=https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8, Type=1, Percent=0.0, DownloadSize=0, State=2, FilePath=null, LocalFile=null, CoverUrl=https://i.loli.net/2021/04/18/WuAUZc85meB6D2Q.jpg, CoverPath=/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/26d0eea3413d57f972c13868d23e2da7.jpg, Title=test3]
M3U8VideoDownloadTask local file.
onDownloadProgress: 100.00%, curTs=64, totalTs=64
removeDownloadQueue size=2,0,2
doParseVideoInfoTask url=https://v3.cdtlas.com/20221119/zimPf0a2/1100kb/hls/index.m3u8
handleOnDownloadSuccess shouldM3U8Merged=true, isHlsType=true
doParseVideoInfoTask url=https://v3.cdtlas.com/20221119/zimPf0a2/1100kb/hls/index.m3u8
VideoMerge doMergeTs taskItem=VideoTaskItem[Url=https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8, Type=1, Percent=100.0, DownloadSize=175072190, State=5, FilePath=26d0eea3413d57f972c13868d23e2da7_local.m3u8, LocalFile=/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/26d0eea3413d57f972c13868d23e2da7/26d0eea3413d57f972c13868d23e2da7_local.m3u8, CoverUrl=https://i.loli.net/2021/04/18/WuAUZc85meB6D2Q.jpg, CoverPath=/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/26d0eea3413d57f972c13868d23e2da7.jpg, Title=test3]
Rejecting re-init on previously-failed class java.lang.Class<com.jeffmony.m3u8library.VideoProcessManager>: java.lang.ExceptionInInitializerError: 
at com.jeffmony.m3u8library.VideoProcessManager com.jeffmony.m3u8library.VideoProcessManager.getInstance() (VideoProcessManager.java:27)
at void com.jeffmony.downloader.VideoDownloadManager.doMergeTs(com.jeffmony.downloader.model.VideoTaskItem, com.jeffmony.downloader.listener.IM3U8MergeResultListener) (VideoDownloadManager.java:647)
at void com.jeffmony.downloader.VideoDownloadManager.access$1400(com.jeffmony.downloader.VideoDownloadManager, com.jeffmony.downloader.model.VideoTaskItem, com.jeffmony.downloader.listener.IM3U8MergeResultListener) (VideoDownloadManager.java:41)
at void com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.lambda$dispatchDownloadInfos$2$VideoDownloadManager$VideoDownloadHandler() (VideoDownloadManager.java:539)
at void com.jeffmony.downloader.-$$Lambda$VideoDownloadManager$VideoDownloadHandler$2NVKttZeyL8RxW86oOV8520RK1o.run() (lambda:-1)
at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:463)
at void java.util.concurrent.FutureTask.run() (FutureTask.java:264)
at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1137)
at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:637)
at void java.lang.Thread.run() (Thread.java:1012)
at void com.jeffmony.downloader.utils.WorkerThreadHandler$MediaWorkerThread.run() (WorkerThreadHandler.java:67)
FATAL EXCEPTION: Video_download_state_thread
Process: com.jeffmony.videodemo, PID: 14928
java.lang.NoClassDefFoundError: com.jeffmony.m3u8library.VideoProcessManager
at com.jeffmony.downloader.VideoDownloadManager.doMergeTs(VideoDownloadManager.java:647)
at com.jeffmony.downloader.VideoDownloadManager.handleOnDownloadSuccess(VideoDownloadManager.java:621)
at com.jeffmony.downloader.VideoDownloadManager.access$1100(VideoDownloadManager.java:41)
at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.dispatchDownloadMessage(VideoDownloadManager.java:578)
at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.handleMessage(VideoDownloadManager.java:530)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.ExceptionInInitializerError
at com.jeffmony.m3u8library.VideoProcessManager.getInstance(VideoProcessManager.java:27)
at com.jeffmony.downloader.VideoDownloadManager.doMergeTs(VideoDownloadManager.java:647)
at com.jeffmony.downloader.VideoDownloadManager.access$1400(VideoDownloadManager.java:41)
at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.lambda$dispatchDownloadInfos$2$VideoDownloadManager$VideoDownloadHandler(VideoDownloadManager.java:539)
at com.jeffmony.downloader.-$$Lambda$VideoDownloadManager$VideoDownloadHandler$2NVKttZeyL8RxW86oOV8520RK1o.run(Unknown Source:2)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
at com.jeffmony.downloader.utils.WorkerThreadHandler$MediaWorkerThread.run(WorkerThreadHandler.java:67)
Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[video_download_worker_pool_thread,5,main] that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:227)
at android.os.Handler.<init>(Handler.java:129)
at com.jeffmony.m3u8library.VideoProcessManager.<clinit>(VideoProcessManager.java:14)
at com.jeffmony.m3u8library.VideoProcessManager.getInstance(VideoProcessManager.java:27) 
at com.jeffmony.downloader.VideoDownloadManager.doMergeTs(VideoDownloadManager.java:647) 
at com.jeffmony.downloader.VideoDownloadManager.access$1400(VideoDownloadManager.java:41) 
at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.lambda$dispatchDownloadInfos$2$VideoDownloadManager$VideoDownloadHandler(VideoDownloadManager.java:539) 
at com.jeffmony.downloader.-$$Lambda$VideoDownloadManager$VideoDownloadHandler$2NVKttZeyL8RxW86oOV8520RK1o.run(Unknown Source:2) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463) 
at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
at java.lang.Thread.run(Thread.java:1012) 
at com.jeffmony.downloader.utils.WorkerThreadHandler$MediaWorkerThread.run(WorkerThreadHandler.java:67)

**Comment by Arey688** [comment]
在华为手机上出现了 [#43](https://github.com/JeffMony/VideoDownloader/issues/43)

**Comment by JeffMony** [comment]
试一下最新的版本
