### ISSUE TITLE
用AndroidStudio自带的虚拟机api32，下载完合并时报 library "libmessage_queue.so" not found 

### ISSUE THREAD

**Issue by yanxiaodongRain** [JeffMony/VideoDownloader#62]
2023-09-27 16:26:33.379 8998-9074/com.home.udianshijia E/CrashReport: Java Crash Happen cause by Video_download_state_thread(61)
2023-09-27 16:26:33.465 8998-9074/com.home.udianshijia E/CrashReport: stack frame :14, has cause false
2023-09-27 16:26:33.466 8998-9074/com.home.udianshijia E/CrashReport: #++++++++++Record By Bugly++++++++++#
2023-09-27 16:26:33.467 8998-9074/com.home.udianshijia E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
2023-09-27 16:26:33.467 8998-9074/com.home.udianshijia E/CrashReport: # PKG NAME: com.home.udianshijia
2023-09-27 16:26:33.467 8998-9074/com.home.udianshijia E/CrashReport: # APP VER: ExpandableTextViewLibrary
2023-09-27 16:26:33.467 8998-9074/com.home.udianshijia E/CrashReport: # SDK VER: 4.1.9.2
2023-09-27 16:26:33.468 8998-9074/com.home.udianshijia E/CrashReport: # LAUNCH TIME: 2023-09-27 08:26:09
2023-09-27 16:26:33.468 8998-9074/com.home.udianshijia E/CrashReport: # CRASH TYPE: JAVA_CRASH
2023-09-27 16:26:33.468 8998-9074/com.home.udianshijia E/CrashReport: # CRASH TIME: 2023-09-27 08:26:33
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: # CRASH PROCESS: com.home.udianshijia
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: # CRASH FOREGROUND: true
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: # CRASH THREAD: Video_download_state_thread
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: # REPORT ID: 0c386c0b-4549-4084-92d1-dd8b5bc309e2
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: # CRASH DEVICE: fail UNROOT
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: # RUNTIME AVAIL RAM:831209472 ROM:3803176960 SD:3803176960
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: # RUNTIME TOTAL RAM:2063716352 ROM:6240665600 SD:6240665600
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: # CRASH STACK: 
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmessage_queue.so" not found 
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at com.jeffmony.m3u8library.VideoProcessManager.loadLibrary(VideoProcessManager.java:22)
        at com.jeffmony.m3u8library.VideoProcessManager.getInstance(VideoProcessManager.java:31)
        at com.jeffmony.downloader.VideoDownloadManager.doMergeTs(VideoDownloadManager.java:650)
        at com.jeffmony.downloader.VideoDownloadManager.handleOnDownloadSuccess(VideoDownloadManager.java:624)
        at com.jeffmony.downloader.VideoDownloadManager.access$1100(VideoDownloadManager.java:41)
        at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.dispatchDownloadMessage(VideoDownloadManager.java:578)
        at com.jeffmony.downloader.VideoDownloadManager$VideoDownloadHandler.handleMessage(VideoDownloadManager.java:530)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2023-09-27 16:26:33.469 8998-9074/com.home.udianshijia E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

![image](https://github.com/JeffMony/VideoDownloader/assets/41563685/7e2ba39b-9d05-409c-b326-0324aee5ad10)

**Comment by JeffMony** [comment]
那肯定是不行的，因为虚拟机用的x86的架构，我没有编译x86的架构.
